const API='https://taskflow-e6yi.onrender.com';let token=localStorage.getItem('taskflow_token');let projects=[];let loginMode=true;
const $=id=>document.getElementById(id);const authSection=$('auth-section'),appSection=$('app-section');
function headers(){return {'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}}
async function api(path,opts={}){const r=await fetch(API+path,{...opts,headers:{...headers(),...(opts.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok){if(r.status===401){logout();}throw Error(d.detail||`Request failed (${r.status})`)}return d}
function showApp(){authSection.classList.add('hidden');appSection.classList.remove('hidden');$('logout').classList.remove('hidden');loadAll()}
function logout(){token=null;localStorage.removeItem('taskflow_token');authSection.classList.remove('hidden');appSection.classList.add('hidden');$('logout').classList.add('hidden')}
$('login-tab').onclick=()=>{loginMode=true;$('login-tab').classList.add('active');$('register-tab').classList.remove('active');$('auth-name').classList.add('hidden');$('auth-submit').textContent='Login'};
$('register-tab').onclick=()=>{loginMode=false;$('register-tab').classList.add('active');$('login-tab').classList.remove('active');$('auth-name').classList.remove('hidden');$('auth-submit').textContent='Create account'};
$('auth-form').onsubmit=async e=>{e.preventDefault();$('auth-error').textContent='';try{const body={email:$('auth-email').value,password:$('auth-password').value};if(!loginMode)body.name=$('auth-name').value;const d=await api(loginMode?'/auth/login':'/auth/register',{method:'POST',body:JSON.stringify(body)});token=d.access_token;localStorage.setItem('taskflow_token',token);showApp()}catch(err){$('auth-error').textContent=err.message}};
$('logout').onclick=logout;
async function loadAll(){await loadProjects();await loadTasks()}
async function loadProjects(){projects=await api('/projects');const s=$('project-select');s.innerHTML=projects.map(p=>`<option value="${p.id}">${escapeHtml(p.name)}</option>`).join('');$('project-list').innerHTML=projects.length?projects.map(p=>`<div class="project-row"><span><b>${escapeHtml(p.name)}</b>${p.description?` — ${escapeHtml(p.description)}`:''}</span><button class="secondary" onclick="removeProject(${p.id})">Delete</button></div>`).join(''):'<p>No projects yet. Create one to start.</p>'}
async function removeProject(id){if(!confirm('Delete this project and its tasks?'))return;try{await api(`/projects/${id}`,{method:'DELETE'});loadAll()}catch(e){alert(e.message)}}
$('new-project').onclick=async()=>{const name=prompt('Project name');if(!name)return;const description=prompt('Description (optional)')||null;try{await api('/projects',{method:'POST',body:JSON.stringify({name,description})});loadProjects()}catch(e){alert(e.message)}};
$('task-form').onsubmit=async e=>{e.preventDefault();try{await api('/tasks',{method:'POST',body:JSON.stringify({title:$('title').value,description:$('description').value||null,status:$('status').value,priority:$('priority').value,due_date:$('due-date').value||null,project_id:Number($('project-select').value)})});e.target.reset();$('form-message').textContent='Task created';loadTasks()}catch(e){$('form-message').textContent=e.message}};
$('quick-add').onclick=async()=>{if(!$('quick-input').value.trim())return;try{await api('/tasks/quick-add',{method:'POST',body:JSON.stringify({description:$('quick-input').value,project_id:Number($('project-select').value)})});$('quick-input').value='';loadTasks()}catch(e){alert(e.message)}};
$('search').oninput=debounce(loadTasks,250);$('filter-status').onchange=loadTasks;$('sort').onchange=loadTasks;
async function loadTasks(){if(!token)return;let p=new URLSearchParams();if($('filter-status').value)p.set('status',$('filter-status').value);if($('search').value.trim())p.set('search',$('search').value.trim());p.set('sort',$('sort').value);try{const tasks=await api('/tasks?'+p);render(tasks)}catch(e){console.error(e)}}
function render(tasks){$('total-count').textContent=tasks.length;$('pending-count').textContent=tasks.filter(t=>t.status==='pending').length;$('progress-count').textContent=tasks.filter(t=>t.status==='in_progress').length;$('done-count').textContent=tasks.filter(t=>t.status==='completed').length;$('task-list').innerHTML=tasks.length?tasks.map(t=>`<article class="task-item ${t.status==='completed'?'done':''}"><div class="task-top"><span class="task-title">${escapeHtml(t.title)}</span><span>#${t.id}</span></div>${t.description?`<p>${escapeHtml(t.description)}</p>`:''}<div class="badges"><span class="badge priority-${t.priority}">${t.priority}</span><span class="badge">${t.status.replace('_',' ')}</span><span class="badge">${t.due_date||'No due date'}</span></div><div class="actions"><button onclick="cycleStatus(${t.id},'${t.status}')">Change status</button><button class="secondary" onclick="removeTask(${t.id})">Delete</button></div></article>`).join(''):'<p>No tasks match your filters.</p>'}
async function cycleStatus(id,status){const next={pending:'in_progress',in_progress:'completed',completed:'pending'}[status];try{await api(`/tasks/${id}`,{method:'PUT',body:JSON.stringify({status:next})});loadTasks()}catch(e){alert(e.message)}}
async function removeTask(id){if(!confirm('Delete this task?'))return;try{await api(`/tasks/${id}`,{method:'DELETE'});loadTasks()}catch(e){alert(e.message)}}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function debounce(fn,ms){let t;return()=>{clearTimeout(t);t=setTimeout(fn,ms)}}
if(token)showApp();
